version: 2

general:
  artifacts:
    - coverage/

defaults: &defaults
  working_directory: ~/ignite-plugin-prop-types
  docker:
    - image: circleci/node:latest-browsers
    
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys: 
            # Find a cache corresponding to this specific package.json checksum
            # when this file is changed, this key will fail
            - ignite-plugin-prop-types-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
            - ignite-plugin-prop-types-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - ignite-plugin-prop-types-{{ .Branch }}
            # Find the most recent cache used from any branch
            - ignite-plugin-prop-types-master
            - ignite-plugin-prop-types-
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: ignite-plugin-prop-types-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
              - .
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/ignite-plugin-prop-types   
      - run:
          name: Lint
          command: yarn lint
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/ignite-plugin-prop-types 
      - run:
          name: Test
          command: yarn test --ci
      - store_test_results:
          path: coverage/junit
      - store_artifacts:
          path: coverage/junit
      - run:
          name: Send CodeCov Results
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_KEY
  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/ignite-plugin-prop-types 
      - run: mkdir ~/.ssh && ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish Library
          command: npm run release
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
              - build
          filters:
            tags:
              only: /.*/
      - test:
          requires:
              - build
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
              - lint
              - test
          filters:
            branches:
              only:
                - master